export const LAYOUTPARAMS = {
    backgroundColor : "#F0F3F4",
    panControlHeight : 15,
    annotationHeight : 30,
    numZoomLevels : 10,
    tileMinPixels : 40,
    tileMaxPixels : 100,
    tileZoomIncrement : 5,
    tileDesiredPixels : 90,
    tileMaxCount : 3000,
    fontSizeTileDefault : 14,
    fontSizeTileSmall : 12,
    fontSizeAnnotations : 14,
    fontSizeErrorMessage : 20,
    zoomIncrementRelative : 0.05,
    zoomMinSizePixels : 50,
    panControlBorderColor : '#222831',
    panControlOpacity : 1,
    panControlBackgroundColor : 'lightgrey',
    sliderMinSizePixels : 20,
    sliderColor : '#393e46',
} 